export const websites = [
  {
    live: "#",
    github: "#",
    image: "/public/web-bg.jpg",
    title: "Title 1",
    id: 1,
  },
  {
    live: "#",
    github: "#",
    image: "/public/web-bg.jpg",
    title: "Title 2",
    id: 2,
  },
  {
    live: "#",
    github: "#",
    image: "/public/web-bg.jpg",
    title: "Title 3",
    id: 3,
  },
  {
    live: "#",
    github: "#",
    image: "/public/web-bg.jpg",
    title: "Title 4",
    id: 4,
  },
  {
    live: "#",
    github: "#",
    image: "/public/web-bg.jpg",
    title: "Title 5",
    id: 5,
  },
  {
    live: "#",
    github: "#",
    image: "/public/web-bg.jpg",
    title: "Title 6",
    id: 6,
  },
  {
    live: "#",
    github: "#",
    image: "/public/web-bg.jpg",
    title: "Title 7",
    id: 7,
  },
];
